[package]
authors     = ['Parallel Team']
description = 'A decentralized lending protocol which allow users to earn "double interests" from staking and lending'
edition     = '2018'
homepage    = 'https://parallel.fi'
name        = 'runtime'
version     = '0.1.0'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.9.0"
dirs = "2.0"
sodalite = "0.3.0"
substrate-subxt = "0.15.0"
substrate-subxt-proc-macro = "0.15.0"
#substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt", branch = "master", default-features = false }
#substrate-subxt-proc-macro = { git = "https://github.com/paritytech/substrate-subxt", branch = "master", default-features = false }
jsonrpsee-utils = "=0.2.0-alpha.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false }
codec = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive", "full"] }

frame-support = "3.0.0"
sp-runtime = "3.0.0"
sp-core = "3.0.0"
sp-keyring = "3.0.0"
log = "0.4.0"
thiserror   = "1.0.24"

[features]
default = ["std"]
std = [
	"sp-runtime/std"
]
